version: '2'
services:
  php-fpm:
    image: clamp/run-php-fpm:latest
    volumes_from:
      - wordpress:ro
      - uploads:rw
    links:
      - db:db
      - memcached:memcached_cluster_1
    environment:
      MEMCACHED_SERVERS: 1
      DB_NAME: "wordpress"
      DB_USER: "admin"
      DB_PASSWORD: "password"
      DB_HOST: "db"
      WP_ENV: "development"
      AUTH_KEY: ""
      SECURE_AUTH_KEY: ""
      LOGGED_IN_KEY: ""
      NONCE_KEY: ""
      AUTH_SALT: ""
      SECURE_AUTH_SALT: ""
      LOGGED_IN_SALT: ""
      NONCE_SALT: ""
      WP_HOME: "http://192.168.99.101/"
      WP_SITEURL: "http://192.168.99.101/"
      # HAProxy Settings
      TCP_PORTS: 9000
      BALANCE: leastconn
  php-proxy:
    image: clamp/run-haproxy:latest
    links:
      - php-fpm
    expose:
      - "9000"
      - "1936"
    ports:
      - "1936:1936"
  nginx:
    image: clamp/run-nginx:latest
    volumes:
      - ./images/run/nginx/config:/etc/nginx
    volumes_from:
      - wordpress:ro
      - uploads:rw
    links:
      - php-fpm:php-fpm-lb
    ports:
      - "80:80"
  memcached:
    image: clamp/run-memcached:latest
  db-data:
    image: clamp/lib-volume
  db:
    image: clamp/run-mysql:latest
    volumes_from:
      - db-data
    environment:
      ON_CREATE_DB: "wordpress"
      MYSQL_PASS: "password"
    ports:
      - "3306:3306"
  uploads:
    image: clamp/lib-volume
    volumes:
      - ./data:/var/www/html/app/uploads
  wordpress:
    image: clamp/run-wordpress:latest
    volumes:
      - ./images/run/wordpress/root/var/www/html:/var/www/html
    volumes_from:
      # Add plugins below
      - akismet:ro
      - application-insights:ro
      - crayon-syntax-highlighter:ro
      - disable-responsive-images:ro
      - google-analytics-for-wordpress:ro
      - jetpack:ro
      - sendgrid-email-delivery-simplified:ro
      - twentysixteen:ro
      - nginx-helper:ro
      # End plugins
  akismet:
    image: clamp/plugin-akismet:latest
  application-insights:
    image: clamp/plugin-application-insights:latest
  crayon-syntax-highlighter:
    image: clamp/plugin-crayon-syntax-highlighter:latest
  disable-responsive-images:
    image: clamp/plugin-disable-responsive-images:latest
  google-analytics-for-wordpress:
    image: clamp/plugin-google-analytics-for-wordpress:latest
  jetpack:
    image: clamp/plugin-jetpack:latest
  sendgrid-email-delivery-simplified:
    image: clamp/plugin-sendgrid-email-delivery-simplified
  twentysixteen:
    image: clamp/theme-twentysixteen
  nginx-helper:
    image: clamp/plugin-nginx-helper
networks:
  default:
    driver: overlay